CREATE DATABASE PAYEASEDB;

USE PAYEASEDB;

CREATE TABLE USERDATA(
    id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    -- [USERID INT IDENTITY(1,1) FOREIGN KEY) NOT NULL,
    COMPANY_NAME NVARCHAR(max) NULL,
    COMPANY_SNAME VARCHAR(10) NULL,
    COMPANY_EMAIL VARCHAR(20) NULL,
ENDUSER_NAME NVARCHAR(max) NULL,
ENDUSER_EMAIL NVARCHAR(max) NULL,
ENDUSER_PASSWORD NVARCHAR(max) NULL,
    ENDUSER_TEL VARCHAR(15) NULL,
    ADMINUSER_EMAIL VARCHAR(20) NULL,
    ADMINUSER_NAME NVARCHAR(max) NULL,
ADMINUSER_PASSWORD NVARCHAR(max) NULL,
    ADMINUSER_TEL VARCHAR(15) NULL,
    TXN_COUNT MEDIUMINT NULL,
    CURRENCY CHAR(4) NULL,
    -- USERROLE VARCHAR(10) NOT NULL,
    DateCREATED DATETIME2 NOT NULL,
)

CREATE TABLE ADMINUSER (
    id INT NOT NULL,
    USERROLE VARCHAR NOT NULL
)

CREATE TABLE ADMINLOGS(
    id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COMPANY_NAME NVARCHAR(max) NULL,
    ACTION_TAKEN VARCHAR(10) NULL,
    ADMIN_EMAIL VARCHAR(20) NULL,
    ADMIN_PHONE_NUMBER VARCHAR(15) NULL,
    CURRENCY CHAR(4) NULL,
    DATETIME DATETIME2 NOT NULL,
)

CREATE TABLE BENEFICIARYDATA(
    id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    USERID INT IDENTITY(1,1) NOT NULL,
    BENE_NAME NVARCHAR(max) NULL,
    BENE_SNAME VARCHAR(10) NULL,
    BENE_EMAIL VARCHAR(20) NULL,
    PHONE_NUMBER VARCHAR(15) NULL,
    BVN VARCHAR(10) NULL,
    CURRENCY CHAR(4) NULL,
    DateCREATED DATETIME2 NOT NULL,
)

CREATE TABLE otp_request (
  `id` INT NOT NULL AUTO_INCREMENT,
  `OTPReqUser` VARCHAR(10) NULL,
  `companyID` INT NULL,
  `requestedTime` DATETIME NULL,
  PRIMARY KEY (`id`));

CREATE TABLE TRANSACTIONS (
    id INT NOT NULL,
    USERID INT IDENTITY(1,1) NOT NULL,
)

CREATE TABLE TRANSACTIONDETAILS (
    id INT NOT NULL,
    USERID INT IDENTITY(1,1) NOT NULL,
)

CREATE TABLE EMAILLOGS(
    id INT PRIMARY KEY NOT NULL,
    USERID INT IDENTITY(1,1) NOT NULL,
    EMAIL VARCHAR(20) NULL,
    STATUS VARCHAR(20) NULL,
    DateADDED DATETIME2 NOT NULL,
)

CREATE TABLE AIRTIMEDATA(
    id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    USERID INT IDENTITY(1,1) NOT NULL,
    COMPANY_NAME NVARCHAR(max) NULL,
    COMPANY_SNAME VARCHAR(10) NULL,
    COMPANY_EMAIL VARCHAR(20) NULL,
    PHONE_NUMBER VARCHAR(15) NULL,
    STATUS NVARCHAR(max) NULL,
    REQUESTDATE DATETIME2 NOT NULL,
)

CREATE TABLE BANKCODE (
    id INT IDENTITY(1,1) NOT NULL,
    CODE INT NULL,
    BANKNAME NVARCHAR(max) NULL,
    SHORT_BANKCODE VARCHAR(10) NULL,
)

-- Backup to a path on the 
-- BACKUP DATABASE PAYEASEDB
-- TO DISK = '/filepath';
-- TO DISK = 'D:\backups\testDB.bak';